// Mocks generated by Mockito 5.4.5 from annotations
// in products_app/test/data/datasources/products_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:fpdart/fpdart.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:products_app/core/errors/failures.dart' as _i12;
import 'package:products_app/core/http_client/http_client_interface.dart'
    as _i7;
import 'package:products_app/products/data/datasources/products_datasource.dart'
    as _i9;
import 'package:products_app/products/data/models/categories/categories_model.dart'
    as _i4;
import 'package:products_app/products/data/models/categories/category_model.dart'
    as _i14;
import 'package:products_app/products/data/models/products/product_model.dart'
    as _i13;
import 'package:products_app/products/data/models/products/products_model.dart'
    as _i3;
import 'package:products_app/products/domain/entities/categories/categories.dart'
    as _i6;
import 'package:products_app/products/domain/entities/products/products.dart'
    as _i5;
import 'package:products_app/products/domain/repositories/products_repository.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsModel_1 extends _i1.SmartFake implements _i3.ProductsModel {
  _FakeProductsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesModel_2 extends _i1.SmartFake
    implements _i4.CategoriesModel {
  _FakeCategoriesModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProducts_3 extends _i1.SmartFake implements _i5.Products {
  _FakeProducts_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategories_4 extends _i1.SmartFake implements _i6.Categories {
  _FakeCategories_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClientInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientInterface extends _i1.Mock
    implements _i7.HttpClientInterface {
  @override
  _i2.Future<T> getRequest<T>(
    String? url, {
    required _i7.ResponseConverter<T>? converter,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRequest,
              [url],
              {
                #converter: converter,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getRequest,
                      [url],
                      {
                        #converter: converter,
                        #queryParameters: queryParameters,
                        #headers: headers,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #getRequest,
                    [url],
                    {
                      #converter: converter,
                      #queryParameters: queryParameters,
                      #headers: headers,
                    },
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getRequest,
                      [url],
                      {
                        #converter: converter,
                        #queryParameters: queryParameters,
                        #headers: headers,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #getRequest,
                    [url],
                    {
                      #converter: converter,
                      #queryParameters: queryParameters,
                      #headers: headers,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> postRequest<T>(
    String? url, {
    required _i7.ResponseConverter<T>? converter,
    Map<String, dynamic>? data,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postRequest,
              [url],
              {#converter: converter, #data: data, #headers: headers},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #postRequest,
                      [url],
                      {#converter: converter, #data: data, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #postRequest,
                    [url],
                    {#converter: converter, #data: data, #headers: headers},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #postRequest,
                      [url],
                      {#converter: converter, #data: data, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #postRequest,
                    [url],
                    {#converter: converter, #data: data, #headers: headers},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> putRequest<T>(
    String? url, {
    required _i7.ResponseConverter<T>? converter,
    Map<String, dynamic>? data,
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putRequest,
              [url],
              {#converter: converter, #data: data, #headers: headers},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #putRequest,
                      [url],
                      {#converter: converter, #data: data, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #putRequest,
                    [url],
                    {#converter: converter, #data: data, #headers: headers},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #putRequest,
                      [url],
                      {#converter: converter, #data: data, #headers: headers},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #putRequest,
                    [url],
                    {#converter: converter, #data: data, #headers: headers},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> deleteRequest<T>(
    String? url, {
    required _i7.ResponseConverter<T>? converter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRequest, [url], {#converter: converter}),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #deleteRequest,
                      [url],
                      {#converter: converter},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #deleteRequest,
                    [url],
                    {#converter: converter},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #deleteRequest,
                      [url],
                      {#converter: converter},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #deleteRequest,
                    [url],
                    {#converter: converter},
                  ),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [ProductsDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsDatasource extends _i1.Mock
    implements _i9.ProductsDatasource {
  @override
  _i2.Future<_i3.ProductsModel> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i2.Future<_i3.ProductsModel>.value(
              _FakeProductsModel_1(this, Invocation.method(#getProducts, [])),
            ),
            returnValueForMissingStub: _i2.Future<_i3.ProductsModel>.value(
              _FakeProductsModel_1(this, Invocation.method(#getProducts, [])),
            ),
          )
          as _i2.Future<_i3.ProductsModel>);

  @override
  _i2.Future<_i4.CategoriesModel> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i2.Future<_i4.CategoriesModel>.value(
              _FakeCategoriesModel_2(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i4.CategoriesModel>.value(
              _FakeCategoriesModel_2(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i2.Future<_i4.CategoriesModel>);

  @override
  _i2.Future<_i3.ProductsModel> getProductsByCategory({
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [], {#slug: slug}),
            returnValue: _i2.Future<_i3.ProductsModel>.value(
              _FakeProductsModel_1(
                this,
                Invocation.method(#getProductsByCategory, [], {#slug: slug}),
              ),
            ),
            returnValueForMissingStub: _i2.Future<_i3.ProductsModel>.value(
              _FakeProductsModel_1(
                this,
                Invocation.method(#getProductsByCategory, [], {#slug: slug}),
              ),
            ),
          )
          as _i2.Future<_i3.ProductsModel>);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i10.ProductsRepository {
  @override
  _i2.Future<_i11.Either<_i12.Failure, _i5.Products>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue:
                _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i5.Products>>(
                    this,
                    Invocation.method(#getProducts, []),
                  ),
                ),
            returnValueForMissingStub:
                _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i5.Products>>(
                    this,
                    Invocation.method(#getProducts, []),
                  ),
                ),
          )
          as _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>);

  @override
  _i2.Future<_i11.Either<_i12.Failure, _i6.Categories>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i2.Future<_i11.Either<_i12.Failure, _i6.Categories>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i6.Categories>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
            returnValueForMissingStub:
                _i2.Future<_i11.Either<_i12.Failure, _i6.Categories>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i6.Categories>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i2.Future<_i11.Either<_i12.Failure, _i6.Categories>>);

  @override
  _i2.Future<_i11.Either<_i12.Failure, _i5.Products>> getProductsByCategory({
    required String? slug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [], {#slug: slug}),
            returnValue:
                _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i5.Products>>(
                    this,
                    Invocation.method(#getProductsByCategory, [], {
                      #slug: slug,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>.value(
                  _i8.dummyValue<_i11.Either<_i12.Failure, _i5.Products>>(
                    this,
                    Invocation.method(#getProductsByCategory, [], {
                      #slug: slug,
                    }),
                  ),
                ),
          )
          as _i2.Future<_i11.Either<_i12.Failure, _i5.Products>>);
}

/// A class which mocks [ProductsModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsModel extends _i1.Mock implements _i3.ProductsModel {
  @override
  List<_i13.ProductModel> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: <_i13.ProductModel>[],
            returnValueForMissingStub: <_i13.ProductModel>[],
          )
          as List<_i13.ProductModel>);

  @override
  int get total =>
      (super.noSuchMethod(
            Invocation.getter(#total),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get skip =>
      (super.noSuchMethod(
            Invocation.getter(#skip),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get limit =>
      (super.noSuchMethod(
            Invocation.getter(#limit),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Products toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeProducts_3(
              this,
              Invocation.method(#toEntity, []),
            ),
            returnValueForMissingStub: _FakeProducts_3(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i5.Products);
}

/// A class which mocks [CategoriesModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesModel extends _i1.Mock implements _i4.CategoriesModel {
  @override
  List<_i14.CategoryModel> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i14.CategoryModel>[],
            returnValueForMissingStub: <_i14.CategoryModel>[],
          )
          as List<_i14.CategoryModel>);

  @override
  set categories(List<_i14.CategoryModel>? _categories) => super.noSuchMethod(
    Invocation.setter(#categories, _categories),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Categories toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeCategories_4(
              this,
              Invocation.method(#toEntity, []),
            ),
            returnValueForMissingStub: _FakeCategories_4(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i6.Categories);
}
