// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4EbR2u_BtDD-TN9kVRL5DRFzWGTkITGo',
    appId: '1:896010752137:web:dec2d4692571b6ef877658',
    messagingSenderId: '896010752137',
    projectId: 'products-app-2e498',
    authDomain: 'products-app-2e498.firebaseapp.com',
    storageBucket: 'products-app-2e498.firebasestorage.app',
    measurementId: 'G-LK30W6NDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Uv479xUR382LheZJvx_AcG18qhY9XuE',
    appId: '1:896010752137:android:4f2d85fa6cacfcde877658',
    messagingSenderId: '896010752137',
    projectId: 'products-app-2e498',
    storageBucket: 'products-app-2e498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3k1Nnm5_165UuKCOLQos-kN6aSqIdPG8',
    appId: '1:896010752137:ios:16b3cc74fd9fd69d877658',
    messagingSenderId: '896010752137',
    projectId: 'products-app-2e498',
    storageBucket: 'products-app-2e498.firebasestorage.app',
    iosBundleId: 'com.example.productsApp',
  );
}
