// // Mocks generated by Mockito 5.4.4 from annotations
// // in products_app/test/presentation/pages/products_page_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i3;
// import 'dart:ui' as _i4;

// import 'package:mockito/mockito.dart' as _i1;
// import 'package:products_app/products/presentation/notifiers/products_page_notifier.dart'
//     as _i2;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeProductsPageState_0 extends _i1.SmartFake
//     implements _i2.ProductsPageState {
//   _FakeProductsPageState_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [ProductsPageNotifier].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockProductsPageNotifier extends _i1.Mock
//     implements _i2.ProductsPageNotifier {
//   @override
//   _i2.ProductsPageState get productsState => (super.noSuchMethod(
//         Invocation.getter(#productsState),
//         returnValue: _FakeProductsPageState_0(
//           this,
//           Invocation.getter(#productsState),
//         ),
//         returnValueForMissingStub: _FakeProductsPageState_0(
//           this,
//           Invocation.getter(#productsState),
//         ),
//       ) as _i2.ProductsPageState);

//   @override
//   set productsState(_i2.ProductsPageState? _productsState) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #productsState,
//           _productsState,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   bool get hasListeners => (super.noSuchMethod(
//         Invocation.getter(#hasListeners),
//         returnValue: false,
//         returnValueForMissingStub: false,
//       ) as bool);

//   @override
//   _i3.Future<void> getProducts() => (super.noSuchMethod(
//         Invocation.method(
//           #getProducts,
//           [],
//         ),
//         returnValue: _i3.Future<void>.value(),
//         returnValueForMissingStub: _i3.Future<void>.value(),
//       ) as _i3.Future<void>);

//   @override
//   void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
//         Invocation.method(
//           #addListener,
//           [listener],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
//         Invocation.method(
//           #removeListener,
//           [listener],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void dispose() => super.noSuchMethod(
//         Invocation.method(
//           #dispose,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void notifyListeners() => super.noSuchMethod(
//         Invocation.method(
//           #notifyListeners,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );
// }
